name: D-IP
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"
permissions:
  contents: write
concurrency:
  group: update-rules
  cancel-in-progress: false
jobs:
  update_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Update rules
        run: bash dev/update-rules.sh

      - name: Commit and push
        run: bash dev/commit-and-push.sh
