name: update-rules
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Update rules
        run: bash dev/main.sh
      - name: Commit push
        run: bash dev/commit-push.sh
